apiVersion: batch/v1
kind: Job
metadata:
  name: validate-balance
spec:
  template:
    metadata:
      name: validate-balance
    spec:
      containers:
      - name: validate-balance
        image: patrocinio/microbank-validate-balance-job:latest
        imagePullPolicy: Always
      restartPolicy: Never
